name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: rodrigopadilhadossantos    
          password: ${{ secrets.DOCKER_PASSWORD }}
